name: online shop

on:
  push:
    branches:
      - main  # Run the workflow on every push to the 'main' branch

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync latest code on self-hosted runner
        run: |
          echo "Pulling the latest code..."
          cd /home/octaloop/actions-runner/online_shop
          git pull origin main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Set working directory
        run: |
          cd /home/octaloop/actions-runner/online_shop

      - name: Build Docker image
        run: |
          docker build --no-cache -t online-image .

      - name: Check if the container is running, then stop and remove it
        run: |
          if docker ps -q --filter "name=online-shop-container"; then
            echo "Stopping and removing container online-shop-container..."
            docker stop online-shop-container || true
            docker rm online-shop-container || true
          else
            echo "Container online-shop-container is not running. Skipping stop and remove."
          fi

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name online-shop-container online-image

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish package to GitHub Packages
        run: |
          echo "Publishing package to GitHub Packages..."
          npm publish --access public
