# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: online shopping app

on:
  push:
    branches:
      - main # Run the workflow on every push to the 'main' branch
    # Yeh wildcard hai, jo har file ko track karega. Aap specific files bhi mention kar sakte hain.

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Sync latest code on self-hosted runner (ensure the latest changes are pulled)
      - name: Sync latest code on self-hosted runner
        run: |
          echo "Pulling the latest code..."
          cd /home/octaloop/online_shop/actions-runner/online_shop
          # Path to self-hosted runner directory
          git pull origin main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17' # Replace with your desired Node.js version

      - name: Set working directory
        run: |
          cd /home/octaloop/online_shop/actions-runner/online_shop

      - name: Build Docker image
        run: |
          docker build --no-cache -t online-shop-image .

      - name: Check if the container is running, then stop and remove it
        run: |
          if docker ps -q --filter "name=online-shop-containers"; then
            echo "Stopping and removing container pp-ecomm-app-container..."
            # Stop and remove the container
            docker stop online-shop-containers || true
            docker rm online-shop-containers || true
          else
            echo "Container online-shop-containers is not running. Skipping stop and remove."
          fi

      - name: Run Docker container
        run: |
          docker run -d -p 5173:5173 --name online-shop-containers online-shop-image
